/********************************************************************
* ec_gamDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ec_gamDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableec_gamDict();
extern void G__cpp_setup_inheritanceec_gamDict();
extern void G__cpp_setup_typetableec_gamDict();
extern void G__cpp_setup_memvarec_gamDict();
extern void G__cpp_setup_globalec_gamDict();
extern void G__cpp_setup_memfuncec_gamDict();
extern void G__cpp_setup_funcec_gamDict();
extern void G__set_cpp_environmentec_gamDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ec_gam.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ec_gamDictLN_TClass;
extern G__linked_taginfo G__ec_gamDictLN_TBuffer;
extern G__linked_taginfo G__ec_gamDictLN_TMemberInspector;
extern G__linked_taginfo G__ec_gamDictLN_TObject;
extern G__linked_taginfo G__ec_gamDictLN_TString;
extern G__linked_taginfo G__ec_gamDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ec_gamDictLN_TList;
extern G__linked_taginfo G__ec_gamDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ec_gamDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ec_gamDictLN_TFile;
extern G__linked_taginfo G__ec_gamDictLN_TTree;
extern G__linked_taginfo G__ec_gamDictLN_TBranch;
extern G__linked_taginfo G__ec_gamDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_TSelector;
extern G__linked_taginfo G__ec_gamDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ec_gamDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ec_gamDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ec_gamDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ec_gamDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__ec_gamDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ec_gamDictLN_TF1;
extern G__linked_taginfo G__ec_gamDictLN_TH2F;
extern G__linked_taginfo G__ec_gamDictLN_TLine;
extern G__linked_taginfo G__ec_gamDictLN_ec_gam;

/* STUB derived class for protected member access */
